// Generated by gencpp from file pick_drop_publisher/pick_drop.msg
// DO NOT EDIT!


#ifndef PICK_DROP_PUBLISHER_MESSAGE_PICK_DROP_H
#define PICK_DROP_PUBLISHER_MESSAGE_PICK_DROP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace pick_drop_publisher
{
template <class ContainerAllocator>
struct pick_drop_
{
  typedef pick_drop_<ContainerAllocator> Type;

  pick_drop_()
    : pickup_loc()
    , dropoff_loc()  {
    }
  pick_drop_(const ContainerAllocator& _alloc)
    : pickup_loc(_alloc)
    , dropoff_loc(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pickup_loc_type;
  _pickup_loc_type pickup_loc;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _dropoff_loc_type;
  _dropoff_loc_type dropoff_loc;





  typedef boost::shared_ptr< ::pick_drop_publisher::pick_drop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_drop_publisher::pick_drop_<ContainerAllocator> const> ConstPtr;

}; // struct pick_drop_

typedef ::pick_drop_publisher::pick_drop_<std::allocator<void> > pick_drop;

typedef boost::shared_ptr< ::pick_drop_publisher::pick_drop > pick_dropPtr;
typedef boost::shared_ptr< ::pick_drop_publisher::pick_drop const> pick_dropConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_drop_publisher::pick_drop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_drop_publisher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pick_drop_publisher': ['/home/gurpreet/workspace/home_service_robot_copy/home_service_robot/catkin_ws/src/pick_drop_publisher/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_drop_publisher::pick_drop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_drop_publisher::pick_drop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_drop_publisher::pick_drop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "711b7b4b694b3604c70b9f871c349cc7";
  }

  static const char* value(const ::pick_drop_publisher::pick_drop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x711b7b4b694b3604ULL;
  static const uint64_t static_value2 = 0xc70b9f871c349cc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_drop_publisher/pick_drop";
  }

  static const char* value(const ::pick_drop_publisher::pick_drop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D pickup_loc\n\
geometry_msgs/Pose2D dropoff_loc\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::pick_drop_publisher::pick_drop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pickup_loc);
      stream.next(m.dropoff_loc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pick_drop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_drop_publisher::pick_drop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_drop_publisher::pick_drop_<ContainerAllocator>& v)
  {
    s << indent << "pickup_loc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pickup_loc);
    s << indent << "dropoff_loc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.dropoff_loc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DROP_PUBLISHER_MESSAGE_PICK_DROP_H
